---
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    ports: 
      - "9200:9200"
    networks: ['stack']
    environment:
      discovery.type: "single-node"
    volumes:
      - "./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    container_name: logstash
    networks: ['stack']
    depends_on: ['elasticsearch']
    volumes:
      - "./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
      - "./config/logstash.yml:/usr/share/logstash/logstash.yml"
    ports: 
      - "25826:25826"
      - "9600:9600"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    ports: 
      - "5601:5601"
    networks: ['stack']
    depends_on: ['logstash']

  calculator:
    build: .
    image: calculator-go-collectd
    ports:
      - "8088:8080"
    container_name: calculator
    networks: ['stack']
    depends_on: ['kibana']

networks: {stack: {}}