# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
    echo Provisioning...
    date > /etc/vagrant_provisioned_at
    sudo snap install go --classic
    sudo snap install docker
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box ="ubuntu/bionic64"

    config.vm.hostname = "golang.dev"

    config.vm.network "private_network", ip: "55.55.55.5"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 3072
        vb.cpus = 2
    end

    config.vm.provision "shell", inline: $script

    config.vm.provision "file", source: "Vagrantfile", destination: "$HOME/Vagrantfile"

    config.vm.provision "file", source: "calculator.go", destination: "$HOME/calculator/calculator.go"

    config.vm.provision "file", source: "runService.sh", destination: "$HOME/calculator/runService.sh"

    config.vm.provision "file", source: "Dockerfile", destination: "$HOME/calculator/Dockerfile"
end