node {
   stage('preparation') {
       checkout([
           $class: 'GitSCM',
           branches: [[name: '*/master']],
           doGenerateSubmoduleConfigurations: false,
           extensions: [[$class: 'CleanBeforeCheckout']],
           userRemoteConfigs: [[credentialsId: 'git-credentials', url: 'https://github.com/EloisaPaz/devops-labs.git']]
       ])
   }
   stage('Test') {
       fileExist = fileExists 'StressTest/Gatling/src/test/scala/calculator/CalculatorSimulation.scala'
        if (fileExist) {
            dir('StressTest/Gatling') {
                sh 'sbt gatling:test'
            }
        } else {
            error 'Gatling test not found'
        }
   }
}
