node {
   stage('preparation') {
       checkout([
           $class: 'GitSCM',
           branches: [[name: '*/master']],
           doGenerateSubmoduleConfigurations: false,
           extensions: [[$class: 'CleanBeforeCheckout']],
           submoduleCfg: [],
           userRemoteConfigs: [[url: 'https://github.com/EloisaPaz/devops-labs.git']]
       ])
   }
   stage('Bake') {
       dir('Packer/docker-go-microservice') {
        sh 'packer build dockerImage.json'
       }
   }
}