# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.provider "virtualbox"
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "private_network", ip: "55.55.55.150"
    config.vm.hostname = "ansible.dev"
    config.vm.provision "shell", inline: <<-SHELL    
        sudo apt update
        sudo apt install software-properties-common
        sudo apt-add-repository --yes --update ppa:ansible/ansible
        sudo apt install -y ansible
    SHELL
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "configuration.yml"
    end   
  end